### ISSUE TITLE
Idea…

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-ads-component#13]
@aintgoin2goa do you think we could make doing this in this repository:-

```js
var meta = document.createElement('meta');
meta.name = 'dfp_site';
meta.content = 'test.next.ft.com';
document.head.appendChild(meta);
```

(or something similar — perhasp that checks if the metatag is there first)

Then we won't need to remember to put in the metatag across all of our applications?

**Comment by aintgoin2goa** [comment]
The O-Ads component shouldn't actually require the meta tag at all - options can be set in code.  however, currently this fails and the code dies unhelpfully at a point much further down in the stack.  That's why the ads component now throws an error if it doesn't find a meta tag

I'm gonna talk to the ads team about this and some issues and get some pull requests going.  I would rather fix the issue than work around it.

Also bear in mind that the site tag may end up being application specific (ft.com has a separate 'site' for each section, the webapp doesn't) so it may be that we keep the meta tags anyway, or put them back, when we get to that point.

**Comment by matthew-andrews** [comment]
Ah cool.  Sounds like you've given this a lot of thought and have a plan.  :-)
